
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIFERENCIA = 24;
  public static final int DO_C = 46;
  public static final int MULT = 19;
  public static final int CHAR = 37;
  public static final int CONST = 11;
  public static final int IGUALACION = 23;
  public static final int FORC = 44;
  public static final int IMPRIMIR = 9;
  public static final int WHILEC = 45;
  public static final int ENTERO = 3;
  public static final int XOR = 31;
  public static final int DOUBLE = 36;
  public static final int DOS_PUNTOS = 12;
  public static final int INT = 35;
  public static final int LLAVE_C = 43;
  public static final int FIN = 47;
  public static final int LLAVE_A = 42;
  public static final int MATCH = 51;
  public static final int NOT = 32;
  public static final int FINCADENA = 8;
  public static final int AND = 30;
  public static final int IGUAL = 13;
  public static final int CARACTER = 6;
  public static final int OR = 29;
  public static final int BOOL = 5;
  public static final int DIV = 22;
  public static final int CONTINUAR = 48;
  public static final int INCREMENTO = 33;
  public static final int IF = 40;
  public static final int UMENOS = 18;
  public static final int ID = 7;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int DECREMENTO = 34;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 20;
  public static final int MENOS = 17;
  public static final int MENOR = 27;
  public static final int PAR_C = 15;
  public static final int PAR_A = 14;
  public static final int MAYOR = 28;
  public static final int POTENCIA = 21;
  public static final int FLECHA = 50;
  public static final int ELSE = 41;
  public static final int DEFAULT = 49;
  public static final int MAYOR_IGUAL = 25;
  public static final int STRING = 39;
  public static final int MENOR_IGUAL = 26;
  public static final int VAR = 10;
  public static final int MAS = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "BOOL",
  "CARACTER",
  "ID",
  "FINCADENA",
  "IMPRIMIR",
  "VAR",
  "CONST",
  "DOS_PUNTOS",
  "IGUAL",
  "PAR_A",
  "PAR_C",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULT",
  "MODULO",
  "POTENCIA",
  "DIV",
  "IGUALACION",
  "DIFERENCIA",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MENOR",
  "MAYOR",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "INT",
  "DOUBLE",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "IF",
  "ELSE",
  "LLAVE_A",
  "LLAVE_C",
  "FORC",
  "WHILEC",
  "DO_C",
  "FIN",
  "CONTINUAR",
  "DEFAULT",
  "FLECHA",
  "MATCH"
  };
}

